### ISSUE TITLE
flynn create without an app name causes unexpected 500

### ISSUE THREAD

**Issue by dstaley** [flynn-archive/flynn-controller#8]
```
$ flynn create
POST http://i69.flynnhub.com:443/apps: controller: unexpected status 500
```

Running `flynn create demo-app` works just fine though. To be honest, I'm not sure where this issue originates, but the error mentioned the controller, so I figured this would be a good place to start.

**Comment by titanous** [comment]
Yeah, the controller doesn't output input validation errors currently. We should also generate app names when one isn't specified (I have a half-written generator kicking around).
